"""Repository port interfaces for clean architecture abstraction."""

from datetime import datetime
from typing import Protocol

from atlas.domain.execution.models import (
    Approval,
    Gate,
    IdempotencyKey,
    ModelCall,
    QuotaLedgerEntry,
    ResourceLock,
    Run,
    RunStatus,
    Step,
    StepStatus,
)
from atlas.domain.focus.models import ActiveFocusPointer, Domain, Entity, Focus
from atlas.domain.knowledge.models import (
    Claim,
    ClaimEvidenceLink,
    ClaimUsage,
    Evidence,
    KnowledgeObjectVersion,
    Snapshot,
    Source,
    Topic,
    TraceabilityChain,
)
from atlas.domain.media.models import RenderArtifact, Storyboard
from atlas.domain.publishing.models import BlackoutRule, Channel, PublishingWindow
from atlas.domain.script.models import Script, TimingPlan


class ExecutionRepositoryPort(Protocol):
    """Port interface for execution, runs, steps, gates, locks, and quota."""

    async def create_run(self, run: Run) -> Run: ...
    async def get_run(self, run_id: str) -> Run: ...
    async def list_runs(self, limit: int = 50) -> list[Run]: ...
    async def update_run_status(
        self,
        run_id: str,
        status: RunStatus,
        completed_at: datetime | None = None,
        error: str | None = None,
    ) -> None: ...
    async def create_step(self, step: Step) -> Step: ...
    async def get_step(self, step_id: str) -> Step: ...
    async def list_steps_for_run(self, run_id: str) -> list[Step]: ...
    async def update_step(
        self,
        step_id: str,
        status: StepStatus,
        output_artifact_ref: str | None = None,
        error: str | None = None,
        completed_at: datetime | None = None,
    ) -> None: ...
    async def create_gate(self, gate: Gate) -> Gate: ...
    async def get_gate(self, gate_id: str) -> Gate: ...
    async def list_gates_for_run(self, run_id: str) -> list[Gate]: ...
    async def list_pending_gates(self) -> list[Gate]: ...
    async def list_all_gates(self) -> list[Gate]: ...
    async def record_approval(self, approval: Approval) -> Approval: ...
    async def list_approvals_for_run(self, run_id: str) -> list[Approval]: ...
    async def acquire_lock(
        self, resource_name: str, holder_id: str, ttl_seconds: int, priority: int = 0
    ) -> ResourceLock: ...
    async def release_lock(self, resource_name: str, holder_id: str) -> None: ...
    async def record_idempotency_key(self, item: IdempotencyKey) -> None: ...
    async def get_idempotency_key(self, key: str) -> IdempotencyKey | None: ...
    async def record_model_call(self, call: ModelCall) -> ModelCall: ...
    async def record_quota_consumption(self, entry: QuotaLedgerEntry) -> QuotaLedgerEntry: ...
    async def get_quota_consumption_summary(self) -> dict[str, dict[str, int]]: ...


class KnowledgeRepositoryPort(Protocol):
    """Port interface for knowledge objects and traceability."""

    async def save_version(
        self, version: KnowledgeObjectVersion, make_current: bool = True
    ) -> KnowledgeObjectVersion: ...
    async def get_version(self, ko_id: str, version: int) -> KnowledgeObjectVersion | None: ...
    async def get_current(self, ko_id: str) -> KnowledgeObjectVersion | None: ...
    async def get_current_for_topic(self, topic_id: str) -> KnowledgeObjectVersion | None: ...
    async def get_history(self, ko_id: str) -> list[KnowledgeObjectVersion]: ...
    async def get_traceability_chain(self, claim_id: str) -> TraceabilityChain: ...


class FocusRepositoryPort(Protocol):
    """Port interface for focus, domains, and entities."""

    async def save_focus(self, focus: Focus) -> Focus: ...
    async def get_focus(self, focus_id: str) -> Focus: ...
    async def set_active_focus(self, focus_id: str, actor_id: str) -> ActiveFocusPointer: ...
    async def get_active_focus(self) -> ActiveFocusPointer | None: ...
    async def save_domain(self, domain: Domain) -> Domain: ...
    async def get_domain(self, domain_id: str) -> Domain | None: ...
    async def save_entity(self, entity: Entity) -> Entity: ...
    async def get_entity(self, entity_id: str) -> Entity | None: ...


class SourceRepositoryPort(Protocol):
    """Port interface for sources, content snapshots, evidence, claims, and topics."""

    async def save_topic(self, topic: Topic) -> Topic: ...
    async def get_topic(self, topic_id: str) -> Topic | None: ...
    async def save_source(self, source: Source) -> Source: ...
    async def get_source(self, source_id: str) -> Source: ...
    async def save_snapshot(self, snapshot: Snapshot) -> Snapshot: ...
    async def get_snapshot(self, snapshot_id: str) -> Snapshot: ...
    async def find_snapshot_by_hash(self, source_id: str, content_hash: str) -> Snapshot | None: ...
    async def save_evidence(self, evidence: Evidence) -> Evidence: ...
    async def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    async def save_claim(self, claim: Claim, actor_id: str, reason: str) -> Claim: ...
    async def get_claim(self, claim_id: str) -> Claim | None: ...
    async def get_claim_history(self, claim_id: str) -> list[Claim]: ...
    async def link_claim_evidence(self, link: ClaimEvidenceLink) -> None: ...
    async def record_claim_usage(self, usage: ClaimUsage) -> ClaimUsage: ...
    async def get_claim_usages(self, claim_id: str) -> list[ClaimUsage]: ...


class PublishingRepositoryPort(Protocol):
    """Port interface for publishing channels, windows, and blackouts."""

    async def save_channel(self, channel: Channel) -> Channel: ...
    async def get_channel(self, channel_id: str) -> Channel | None: ...
    async def save_window(self, window: PublishingWindow) -> PublishingWindow: ...
    async def get_windows(
        self,
        channel_id: str,
        platform: str | None = None,
        content_format: str | None = None,
        day_of_week: int | None = None,
    ) -> list[PublishingWindow]: ...
    async def save_blackout_rule(self, rule: BlackoutRule) -> BlackoutRule: ...
    async def get_active_blackout_rules(self) -> list[BlackoutRule]: ...


class ProductionRepositoryPort(Protocol):
    """Port interface for per-Run production artifacts (SPEC §6 stages 8-18)."""

    async def save_script(self, script: Script, run_id: str) -> Script: ...
    async def get_script(self, script_id: str) -> Script: ...
    async def save_timing_plan(self, plan: TimingPlan, run_id: str) -> TimingPlan: ...
    async def get_timing_plan(self, timing_plan_id: str) -> TimingPlan: ...
    async def get_timing_plan_for_script(self, script_id: str) -> TimingPlan: ...
    async def save_storyboard(self, storyboard: Storyboard, run_id: str) -> Storyboard: ...
    async def get_storyboard(self, storyboard_id: str) -> Storyboard: ...
    async def save_render_artifact(self, artifact: RenderArtifact) -> RenderArtifact: ...
    async def get_render_artifact(self, artifact_id: str) -> RenderArtifact: ...
    async def list_render_artifacts(self, run_id: str) -> list[RenderArtifact]: ...
